version: '3.8'

services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: nps-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-nps_system}
      MYSQL_USER: ${DB_USER:-nps_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-nps_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/fix_schema.sql:/docker-entrypoint-initdb.d/02-fix_schema.sql
    ports:
      - "3306:3306"
    networks:
      - nps-network

  # Aplicación PHP
  app:
    build: .
    container_name: nps-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-nps_system}
      - DB_USER=${DB_USER:-nps_user}
      - DB_PASSWORD=${DB_PASSWORD:-nps_password}
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    ports:
      - "80:80"
    networks:
      - nps-network

  # phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nps-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USER:-nps_user}
      - PMA_PASSWORD=${DB_PASSWORD:-nps_password}
    ports:
      - "8080:80"
    networks:
      - nps-network

volumes:
  mysql_data:

networks:
  nps-network:
    driver: bridge 